from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Tetris', src, depend = ['PKG_USING_TETRIS'], CPPPATH = CPPPATH)

Return('group')
